version: 2
jobs:
  build:
    working_directory: /opt/workspace
    docker:
      - image: adaptmobile/android-docker:27
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Dependencies
          # Build docs using Dokka 
          command: cd $(/opt/tools/findGradleW.sh) && ./gradlew dokka
      - run:
          name: Run script
          # Build docs using Dokka
          command: |
            cd docs/
            ./run.sh
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: /opt
          # Must be relative path from root
          paths:
            - workspace

  deploy:
    working_directory: /opt/workspace
    docker:
      - image: adaptmobile/android-docker:27
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cf:26:50:96:ff:22:00:f4:1a:98:bc:9c:cd:8c:a9:52"
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /opt
      - run:
          name: Remove old folder
          command: |
            git config --global user.email "adaptcircleci@example.com"
            git config --global user.name "Circle CI"
            git add docs
            git commit -m "Update docs"
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push --set-upstream origin feature/dokka-doc-gitbook
      - run:
          name: Install Firebase CLI tool
          command: |
            npm install -g firebase-tools
      - run:
          name: Deploy to Firebase
          command: firebase deploy --only hosting --token=$FIREBASE_DEPLOY_TOKEN


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - feature/dokka-doc-gitbook
                - master