import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
  /**
   * https://developer.android.com/jetpack/androidx
   */
  const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

  /**
   * http://tools.android.com
   */
  const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
      Versions.constraintlayout

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

  /**
   * https://developer.android.com/studio
   */
  const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

  /**
   * https://developer.android.com/studio
   */
  const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
      Versions.com_android_tools_build_gradle

  /**
   * https://developer.android.com/studio
   */
  const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

  /**
   * https://github.com/bluelinelabs/Conductor
   */
  const val conductor_rxlifecycle2: String = "com.bluelinelabs:conductor-rxlifecycle2:" +
      Versions.com_bluelinelabs

  /**
   * https://github.com/bluelinelabs/Conductor
   */
  const val conductor_support: String = "com.bluelinelabs:conductor-support:" +
      Versions.com_bluelinelabs

  /**
   * https://github.com/bluelinelabs/Conductor
   */
  const val conductor: String = "com.bluelinelabs:conductor:" + Versions.com_bluelinelabs

  /**
   * https://github.com/bumptech/glide
   */
  const val glide: String = "com.github.bumptech.glide:glide:" + Versions.glide

  /**
   * https://github.com/dcendents/android-maven-gradle-plugin
   */
  const val android_maven_gradle_plugin: String =
      "com.github.dcendents:android-maven-gradle-plugin:" + Versions.android_maven_gradle_plugin

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val material: String = "com.google.android.material:material:" + Versions.material

  /**
   * https://github.com/square/retrofit/
   */
  const val retrofit: String = "com.squareup.retrofit2:retrofit:" + Versions.retrofit

  /**
   * https://github.com/xwray/groupie
   */
  const val groupie_kotlin_android_extensions: String =
      "com.xwray:groupie-kotlin-android-extensions:" + Versions.com_xwray

  /**
   * https://github.com/xwray/groupie
   */
  const val groupie: String = "com.xwray:groupie:" + Versions.com_xwray

  const val de_fayard_buildsrcversions_gradle_plugin: String =
      "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
      Versions.de_fayard_buildsrcversions_gradle_plugin

  /**
   * https://github.com/ReactiveX/RxAndroid
   */
  const val rxandroid: String = "io.reactivex.rxjava2:rxandroid:" + Versions.rxandroid

  /**
   * https://github.com/ReactiveX/RxJava
   */
  const val rxjava: String = "io.reactivex.rxjava2:rxjava:" + Versions.rxjava

  /**
   * https://github.com/ReactiveX/RxKotlin
   */
  const val rxkotlin: String = "io.reactivex.rxjava2:rxkotlin:" + Versions.rxkotlin

  /**
   * https://github.com/wasabeef/Blurry
   */
  const val blurry: String = "jp.wasabeef:blurry:" + Versions.jp_wasabeef

  /**
   * https://github.com/wasabeef/recyclerview-animators
   */
  const val recyclerview_animators: String = "jp.wasabeef:recyclerview-animators:" +
      Versions.jp_wasabeef

  /**
   * http://greenrobot.org/eventbus/
   */
  const val eventbus: String = "org.greenrobot:eventbus:" + Versions.eventbus

  const val dokka_android_gradle_plugin: String =
      "org.jetbrains.dokka:dokka-android-gradle-plugin:" + Versions.dokka_android_gradle_plugin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions_runtime: String =
      "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions: String = "org.jetbrains.kotlin:kotlin-android-extensions:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_stdlib_jdk7: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://github.com/chrisjenx/Calligraphy
   */
  const val calligraphy: String = "uk.co.chrisjenx:calligraphy:" + Versions.calligraphy
}
